config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :categories

  get 'categories/index'
  get 'categories/show'
  get 'categories/new'
  get 'categories/edit'
  get 'categories/delete'

  get 'pages/home'
  get 'pages/erb_demo'
  get 'pages/render_demo'
  get 'pages/redirect_demo'
  

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to(:action => 'index')
    else
      render('new')
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  
  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      redirect_to(:action => 'show', :id => @category.id)
    else
      render('index')
    end
  end

  def delete
  end


  private
  
  def category_params
    params.require(:category).permit(:name, :thumburl)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end

	def erb_demo
	end

	def render_demo
		render :home
	end

	def redirect_demo
		redirect_to(:action => 'home')
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>

  <div class="name">
  	<%= f.label :name %>
  	<%= f.text_field :name %>
  </div>

  <div class="thumburl">
		<%= f.label :thumburl %>
		<%= f.url_field :thumburl %>
  </div>

  <div class="actions">
		<%= f.submit %>
  </div>

<% end %>

app/views/categories/delete.html.erb
<h1>Categories#delete</h1>
<p>Find me in app/views/categories/delete.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

<h1>Edit Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="categories">
      <div class="container">
        <div class="row">
          <div class="col-md-2">
            <h2>Categories</h2>
            <p>Explore our latest categories from around the world.</p>
          </div>
          <div class="col-md-8">
            <% @categories.in_groups_of(3).each do |categories| %>
              <% categories.select! {|x| !x.nil?} %>
              <div class='row'>
                <% categories.each do |category| %>
                  <div class='col-md-4'>
                    <div class="thumbnail">
                        <img src= <%= category.thumburl %> >
                        <div class="caption">
                          <span class="listing-title"><%= category.name %></span>
                          <span><%= link_to "Edit", edit_category_path(category.id) %></span>
                          <span><%= link_to 'Show', category %></span>
                          <td><%= link_to 'Delete', categories_delete_path(:id => category.id) %></td>
                        </div>
                      </div>
                    </div>
                <% end %>
              </div>
            <% end %>

          </div>
        </div>

      </div>
    </div>

<table>
  <thead>
    <tr>
      <th>Category name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <div class="thumbnail">
           <img src= <%=category.thumburl %> >
        <div>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Delete', categories_delete_path(:id => category.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

<h1>New Category</h1>

	<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<!-- <h1>Categories#show</h1> -->
<!-- <p>Find me in app/views/categories/show.html.erb</p> -->


<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Thumburl:</strong>
  <%= @category.thumburl %>
  <!-- Show image for each -->
   <div class="thumbnail">
      <img src= <%=@category.thumburl %> >
    <div>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EtsyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

    <!-- Bootstrap -->
    <!--<link href="css/bootstrap.min.css" rel="stylesheet">-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

    
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/erb_demo.html.erb
<%= "This is the erb demo template." %>
<% "goodbye world" %>
<%= "hello world" %>

app/views/pages/home.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h1>Shop directly from people around the world.</h1>
      </div>
    </div>
  </div>
</div>

<div class="trending">
  <div class="container">
    <h2>Recent Favorites</h2>
    <p>Discover finds from around the marketplace.</p>
    <div class="row trending-listing">
      <div class="col-md-4">
        <div class="thumbnail">
          <img src="https://img1.etsystatic.com/034/0/6705395/il_340x270.542888787_ggy4.jpg">
          <div class="caption">
            <span class="listing-title">Large gold leather bag</span>
            <span class="listing-price">$100.00</span>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="thumbnail">
          <img src="https://img1.etsystatic.com/010/0/6957353/il_340x270.427320275_pxiv.jpg">
          <div class="caption">
            <span class="listing-title">Large gold leather bag</span>
            <span class="listing-price">$15.00</span>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="thumbnail">
          <img src="https://img1.etsystatic.com/038/0/6566540/il_340x270.566511947_1r1t.jpg">
          <div class="caption">
            <span class="listing-title">Large gold leather bag</span>
            <span class="listing-price">$160.00</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/redirect_demo.html.erb
<%= "This is your redirect demo template" %>

app/views/pages/render_demo.html.erb
<%= "This is your render_demo template." %>